#----------#
# Pointers |
#----------#
[DEFAULT]
databaseurl = redis://nott-server.ster.kuleuven.be:6379
opcuaaddress = opc.tcp://10.33.179.151:4840
frame_directory = \\nott-server.ster.kuleuven.be\Frames
# frame_directory = C:\Users\fys-lab-ivs\Documents\Frames\ 
linux_frame_directory = /home/labo/frames
[SCIFYSIM]
# Config file for SCIFYsim
config = /home/labo/src/NOTTControl/nottcontrol/nott_config.ini

#-------------------#
# Hardware defaults |
#-------------------#
[DL]
default_speed = 50
[PIEZO]
# ADU / um
default_gains = 255,461.31166385,273.60503791,295.80487777
# um
default_offsets = 0,0,0,0
# ADU
default_min_raw = 0
default_max_raw = 4000
[TIPTILT]
default_speed = 10

#-----------#
# IR camera |
#-----------#
[CAMERA]
# Time used for stamping frames & redis entries. If True, camera time. If False, estimated Windows machine time
use_camera_time = False
# If True, values of counts (avg,min,max) recorded within the rois are written to the redis database.
# If False, rely on the transfer of full frames (Windows -> Linux) to get these values.
record_rois = False

# If True, frames saved to local storage are windowed.
windowing = True
window_w = 160
window_h = 150
window_x = 250
window_y = 90
# ROI positions & sizes as defined in the FULL (non-windowed) frame.
# Loading/saving ROIs in the nottcontrol GUI uses below fields.
ROI 10 = 345,105,8,105
ROI 9 = 257,105,8,105
ROI 8 = 268,105,8,105
ROI 7 = 277,105,8,105
ROI 6 = 286,105,8,105
ROI 5 = 296,105,8,105
ROI 4 = 306,105,8,105
ROI 3 = 316,105,8,105
ROI 2 = 325,105,8,105
ROI 1 = 334,105,8,105
# Matching channel labels to ROI indices
channel_labels = P1,P2,I1,I2,I3,I4,P3,P4,B1,B2
roi_indices = 1,2,3,4,5,6,7,8,9,10
# Custom pixel-to-wavelength mapping (pixel row, micron), top-to-bottom. Length should correspond to the height of the outputs on te camera.
pix_to_lamb = 1,2,3,4,5,6,7,8,9,10
# Range of wavelengths viewed on camera (micron) # TBD
low_lamb =  3.5
up_lamb = 4.0
low_index = 30.0
up_index = 50.0

roi1 = 383.14055376779913,326.1362205565628,4.695574827550445,4.730297918764165
roi2 = 377.09301858190946,326.0903792857764,4.810794389421858,4.813500766193158
roi3 = 372.05877068166444,326.0950571371673,4.803916792104815,4.83838412391782
roi4 = 366.0588323038446,326.05626248609343,4.908820212354783,4.885505965298762
roi5 = 361.132381499461,326.08103476646534,4.832741971509449,4.881096091508539
roi6 = 355.0665826808992,326.068725418899,4.873372211119033,4.903651790279582
roi7 = 350.0912357708507,326.0803377991091,4.8856350805367015,4.890432854183587
roi8 = 344.099805242841,326.0669980316478,4.8611608398513795,4.893181156119795
roi9 = 383.1209686576676,332.12019298239534,4.67963773210073,4.766118035720126
roi10 = 357.4664191943618,346.49439213779146,10.697831477398154,14.012472196171814

roi 10 = 343.46540094023857,167.78378312027394,2.932926669711321,2.91697201376820
roi 9 = 328.47917555360016,168.51198231466958,2.9055735187287155,2.890574100226928
roi 8 = 304.07383495854396,168.06978782257602,2.946209744627879,2.937358196429898
roi 7 = 311.9555430061598,167.94449077174843,2.9292656879732704,2.9512044920048197
roi 6 = 321.01229086195286,168.06704929087383,2.9313990787707667,2.9208311968606324
roi 5 = 331.9438872690904,168.26707547357765,2.869263257352088,2.843292551837294
roi 4 = 340.07230085070455,168.0331024919212,2.9213975345015797,2.915996594955402
roi 3 = 350.95793834824366,168.06959072891772,2.914366319199928,2.9421466758680026
roi 2 = 359.99204964095054,168.03964877661028,2.9127110404388645,2.9086342921387995
roi 1 = 368.142053499904,167.99010364095645,2.927210411903843,2.9265924236565297

[redis]
# Time it takes for the Infratec camera to write its ROI values to Redis, estimated to be about 15 ms. An overestimation is used.
t_write = 20

#---------------#
# DL/piezo scan |
#---------------#
[cophasing]
dl_speed = 0.02 #mm/s

#--------------------#
# nott_TTM_alignment |
#--------------------#
[tip_tilt_control]
#units are in mm
step_default = 0.00001
step_localization = 0.02
step_optimisation = 0.005
speed = 0.002
[injection]
# ------- #
# General |
# ------- #   
# bool_UT is True when NOTT is connected to the UTs.
bool_UT = True
# bool_offset is True when actuator motions should incorporate empirical offsets, retrieved from the simulated grids.
bool_offset = False
# --------#
# Spirals |
# ------- #
# If (photo - noise_mean) / noise_std > fac_loc, the spiral is not started (localization spiral).
fac_loc = 200
# How much should the SNR improvement be for injection to be claimed (localization spiraling)?
SNR_inj = 10
# How much samples of dt_sample should have a SNR improvement > SNR_inj for injection to be called (localization spiral)
Ncrit = 2
# Boundary stop condition for on-sky spiraling (localization spiral).
Nsteps_skyb = 10
# One measurement (noise/photometric) should consist of N exposures (localization & optimization spiraling).
Nexp = 1
# --------- #
# Actuators |
# --------- #
# An actuator motion smaller than disp_double (mm) is carried out by a double-step motion.
disp_double = 0.0005
# The overshoot stepsize of the double-step motion (mm).
step_double = 0.001
# The speed of the double-step motion (mm/s).
speed_double = 0.002

#-----------------------#
# Lucid visible cameras |
#-----------------------#
[connection]
im_ip = 10.33.179.61
pup_ip = 10.33.179.45
[stream_im]
StreamAutoNegotiatePacketSize = True
StreamPacketResendEnable = True
[stream_pup]
StreamAutoNegotiatePacketSize = True
StreamPacketResendEnable = True
[readout_im]
ExposureAuto = Off
AcquisitionFrameRateEnable = True
AcquisitionFrameRate = 1.4
ExposureTimeSelector = Common 
ExposureTime = 56318.0
GainAuto = Off
Gain = 12.0
BlackLevel = 0.0
GammaEnable = True 
Gamma = 1.0
Width = 200
Height = 300
OffsetX = 1800
OffsetY = 1000
[readout_pup]
ExposureAuto = Off
AcquisitionFrameRateEnable = True
AcquisitionFrameRate = 0.5
ExposureTimeSelector = Common 
ExposureTime = 1959860.944
GainAuto = Off
Gain = 48.0
BlackLevel = 0.0
GammaEnable = True 
Gamma = 1.0
Width = 3072
Height = 2048
OffsetX = 0
OffsetY = 0
[fit_pup]
# Standard deviation of Gaussian kernel used for image smoothening
sigma = 50
# Amounts of pixels per bin
mybinx = 4
mybiny = 4
# Percentile thresholds for gradient-based edge detection
perc_grad_low = 80
perc_grad_high = 95
# Percentile threshold for intensity-based filtering of high gradient pixels
perc_int = 80
[fit_im]
# Amount of pixels per bin
mybinx = 2
mybiny = 2
# Percentile thresholds for gradient-based edge detection
perc_grad_low = 99.9
perc_grad_high = 100
# Percentile threshold for intensity-based filtering of high gradient pixels
perc_int = 99.9
[ref_pup]
# (pos_x,pos_y,radius) in px : 
beam1 = (1339,717,629)
beam2 = (1313,678,661)
beam3 = (1323,711,658)
beam4 = (1389,721,692)
[ref_im] 
# (pos_x,pos_y,radius) in px : 
beam1 = (103,77,3)
beam2 = (97,129,3)
beam3 = (93,175,3)
beam4 = (88,225,3)
[convert_dict]
im_ip = String
pup_ip = String
StreamAutoNegotiatePacketSize = Bool
StreamPacketResendEnable = Bool
ExposureAuto = String
AcquisitionFrameRateEnable = Bool
AcquisitionFrameRate = Float
ExposureTimeSelector = String
ExposureTime = Float
GainAuto = String
Gain = Float
BlackLevel = Float
GammaEnable = Bool
Gamma = Float
Width = Int
Height = Int
OffsetX = Int
OffsetY = Int
sigma = Int
mybinx = Int
mybiny = Int
perc_grad_low = Float
perc_grad_high = Float
perc_int = Float
N = Int
rfit = Int
beam1 = IntTuple
beam2 = IntTuple
beam3 = IntTuple
beam4 = IntTuple
